name: Continuous integration

on:
  push:
    branches: [main]
  pull_request:

permissions: {}

jobs:
  build-test:
    name: Build and test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read

    services:
      postgres:
        image: postgis/postgis:14-master
        ports:
          - '5449:5432'
        env:
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: zuvinimas_test
          TZ: 'Etc/GMT'
          PGTZ: 'Etc/GMT'
        options: >-
          --health-cmd pg_isready
          --health-interval 2s
          --health-timeout 2s
          --health-retries 30

    env:
      DB_CONNECTION: postgresql://postgres:postgres@localhost:5449/zuvinimas_test
      REDIS_CONNECTION: redis://localhost:6379

    steps:
      - uses: actions/checkout@v3

      - name: Set up node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Ensure postgis extension is enabled
        run: |
          PGPASSWORD=postgres psql -h localhost -p 5449 -U postgres -d zuvinimas_test \
            -c "CREATE EXTENSION IF NOT EXISTS postgis;"

      - name: Build
        run: yarn run build

      - name: Run tests
        run: yarn test

  validate-docker-build:
    name: Validate if docker image builds
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build & tag docker image
        uses: AplinkosMinisterija/reusable-workflows/.github/actions/docker-build-tag-push@main
        with:
          environment: test
          push: false
