name: Cleanup

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  clean-ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      packages: write
    steps:
      - name: Generate image name
        id: image
        run: |
          image=$(echo ghcr.io/AplinkosMinisterija/biip-zuvinimas-api | awk -F/ '{print $NF}')
          echo "image-name=${image}" >> "$GITHUB_OUTPUT"

      - name: Delete old Docker images
        uses: actions/delete-package-versions@v4
        with:
          package-name: ${{ steps.image.outputs.image-name }}
          package-type: container
          ignore-versions: '^(?!development-).*'
