name: Deploy to Development

on:
  workflow_dispatch:

concurrency: deploy-to-development

jobs:
  docker-build-push:
    name: Build & push docker image
    uses: AplinkosMinisterija/reusable-workflows/.github/workflows/docker-build-push.yml@main
    permissions:
      contents: read
      packages: write
    with:
      docker-image: ghcr.io/aplinkosministerija/biip-zuvinimas-api
      environment: development
      runs-on: ubuntu-latest
      push: true