name: Deploy to Production
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

concurrency: deploy-to-production

jobs:
  publish-production-release:
    name: Publish production Docker image
    uses: AplinkosMinisterija/reusable-workflows/.github/workflows/docker-build-push.yml@main
    permissions:
      contents: read
      packages: write
    with:
      docker-image: ghcr.io/AplinkosMinisterija/biip-zuvinimas-api
      environment: production
      runs-on: ubuntu-latest
      latest-tag: true
      push: true