name: Deploy to Development

on:
  workflow_dispatch:

concurrency:
  group: deploy-development
  cancel-in-progress: true

jobs:
  deploy-development:
    name: Build & push docker image
    runs-on: ubuntu-latest
    environment: Development
    timeout-minutes: 15
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: AplinkosMinisterija/reusable-workflows/.github/actions/docker-build-tag-push@main
        with:
          docker-image: ghcr.io/aplinkosministerija/biip-zuvinimas-api
          registry-password: ${{secrets.GITHUB_TOKEN}}
          environment: development
          runs-on: ubuntu-latest
          push: true
