name: Deploy to Production

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

concurrency: deploy-to-production

permissions:
  contents: read
  packages: write

jobs:
  docker-build-push:
    name: Build & push docker image
    uses: AplinkosMinisterija/reusable-workflows/.github/workflows/docker-build-push.yml@main
    with:
      docker-image: ghcr.io/AplinkosMinisterija/biip-zuvinimas-api
      environment: production
      runs-on: ubuntu-latest
      latest-tag: true