name: Deploy to Development

on:
  workflow_dispatch:

jobs:
  deploy-development:
    name: Deploy development
    uses: AplinkosMinisterija/reusable-workflows/.github/workflows/biip-deploy.yml@deploy-using-github-app
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      environment: Development
      docker-image: ghcr.io/AplinkosMinisterija/biip-zuvinimas-api
