# Based on https://github.com/axios/axios/blob/v1.x/.github/workflows/release.yml
name: Release to production

on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: Choose release type
        options:
          - auto
          - patch
          - minor
          - major
        default: auto
      dry:
        type: boolean
        description: Dry release
        default: false

jobs:
  release-production:
    name: Release to production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Set up node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TYPE_ARG: ${{ fromJSON('{"auto":"", "patch":"--patch", "minor":"--minor", "major":"--major"}')[github.event.inputs.type] }}
          DRY_ARG: ${{ github.event.inputs.dry == 'true' && '--dry-run' || '' }}
        run: npm run release -- --ci --verbose $TYPE_ARG $BETA_ARG $DRY_ARG
